// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyKing.Persistence.Database;

#nullable disable

namespace PartyKing.Persistence.Migrations
{
    [DbContext(typeof(WriterDbContext))]
    [Migration("20250807181604_AddedUploadedImagesSeed")]
    partial class AddedUploadedImagesSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("PartyKing.Domain.Entities.SlideshowImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteAfterPresentation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01988505-d093-7975-b654-e08ccf29268f"),
                            ContentType = "IMG_2332.png",
                            DeleteAfterPresentation = false,
                            ImageName = "image/png",
                            ImageUrl = "SampleImages/Uploaded/IMG_2332.png"
                        },
                        new
                        {
                            Id = new Guid("01988506-1bb9-7308-a454-183052930ad6"),
                            ContentType = "IMG_7758.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_7758.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988506-4eee-760b-aea7-9cbab5f126f6"),
                            ContentType = "IMG_7296.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_7296.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988506-9009-7274-9825-a38a703ec929"),
                            ContentType = "IMG_6050.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_6050.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988506-bfaf-7985-b161-d1555555a762"),
                            ContentType = "IMG_5420.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_5420.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988507-0487-7618-bc80-bbecfec7479c"),
                            ContentType = "IMG_5565.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_5565.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988507-2f0c-758b-b577-65ceeb9b1dbe"),
                            ContentType = "IMG_4948.png",
                            DeleteAfterPresentation = false,
                            ImageName = "image/png",
                            ImageUrl = "SampleImages/Uploaded/IMG_4948.png"
                        },
                        new
                        {
                            Id = new Guid("01988507-52ae-71df-9a53-918a85a61a25"),
                            ContentType = "IMG_4943.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_4943.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988507-ac6b-73ae-a586-902f2a46f4b0"),
                            ContentType = "IMG_4965.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_4965.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988507-f7bc-73cc-8505-12313d4419e3"),
                            ContentType = "IMG_4437.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_4437.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-73dd-ae67-29b2edf9f268"),
                            ContentType = "IMG_3375.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3375.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-708d-aa86-4c8edb216623"),
                            ContentType = "IMG_3380.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3380.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-76f2-a1d2-bfd6c4c213df"),
                            ContentType = "IMG_3379.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3379.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-7855-9c0c-52c5524614b4"),
                            ContentType = "IMG_3382.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3382.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-744e-9811-eca74c350a98"),
                            ContentType = "IMG_3377.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3377.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-7be5-a608-95918f46d42c"),
                            ContentType = "IMG_3381.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3381.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-7bfd-94a8-8d8aad6cdeb2"),
                            ContentType = "IMG_3378.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3378.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-79da-8602-c6c2c11dae72"),
                            ContentType = "IMG_3374.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3374.jpeg"
                        },
                        new
                        {
                            Id = new Guid("01988512-f059-718b-affa-b04bdd32f330"),
                            ContentType = "IMG_3376.jpeg",
                            DeleteAfterPresentation = false,
                            ImageName = "image/jpeg",
                            ImageUrl = "SampleImages/Uploaded/IMG_3376.jpeg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
